name: Prod code deploy

on:
    workflow_dispatch:

jobs:
  deploy:
    env:
      perm_env: prod
    strategy:
      matrix:
        machine: [backend, cron, taskrunner]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Save ssh deploy key to a file
      run: |
        echo "$SSH_KEY" > key
        chmod 400 key
      env:
        SSH_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
    - name: Generate Inventory
      run: ./scripts/generate_inventory.sh ${{ env.perm_env }} ${{ matrix.machine }}
    - name: Send start Slack notification
      run: curl -X POST -H 'Content-type:application/json' --data '{"text":"${{ env.perm_env }} deploy started"}' https://hooks.slack.com/services/TBBFM3TEY/BJKUMT4CC/${{ secrets.SLACK_KEY }}
    - name: Run deploy
      run: ansible-playbook provisioners/deploy-${{ matrix.machine }}.yml -vv -e "perm_env=${{ env.perm_env }}" -i inventory.ini
      env:
        ANSIBLE_PIPELINING: True
        ANSIBLE_HOST_KEY_CHECKING: False
    - name: Send end Slack notification
      run: curl -X POST -H 'Content-type:application/json' --data '{"text":"${{ env.perm_env }} deploy complete"}' https://hooks.slack.com/services/TBBFM3TEY/BJKUMT4CC/${{ secrets.SLACK_KEY }}
